[auth]
id = "teacherui"
secret = "UrqTSjfnaWsaJHCTfGeU6YyEVNa3c2QzE8GrTLcoK1kljsNB3HrG6jXAGI6q8wKR"

[server]
local = true
host = "localhost"
port = 8080
root_path = "./../frontend/public/"
glp_files_path = "./glp_files/"
beaconing_api_route = "https://core.beaconing.eu/api/"

[localisation]
map_file = "./trans.map"
key_file = "./trans.keys"

[debug]
grmon = false
